### ISSUE TITLE
Problema con firma

### ISSUE THREAD

**Issue by asalgado0391** [johann04/xades-signer-cr#1]
Buenas Tardes @johann04 estuve probando su codigo y genera casi perfecta la firma con el unico detalle que Hacienda me retorna el mensaje **El contribuyente que firma la factura electronica no es el emisor**
Podria indicarme si es que el codigo contiene, en alguna parte quemada, funcionalidad para que la firma la genere para un emisor especifico.

Gracias

**Comment by johann04** [comment]
si, la carpeta test-data tiene mi certificado, con mis datos... tienes que ir a ATV a solicitar tu información.

**Comment by asalgado0391** [comment]
Correcto :) yo mando mis datos empleando el comando 

**java -jar release/xadessignercr.jar sign ../test-data/cert.p12 5678 ../test-data/factura.xml ../test-data/out.xml**

con mis credenciales y la firma se genera correctamente, sin embargo me retorna ese error

**Comment by johann04** [comment]
y el xml también? osea, ese cert.p12 lo tienes que descargar, y usar el pin que vos le pusiste, eso pasa la firma bien, luego cuando haces el send, ahí tienes que poner los demás datos (el usuario y password que generaste también en hacienda)

**Comment by asalgado0391** [comment]
Correcto, yo descargue los datos y uso la ruta donde los guarde desde el comando java -jar, sin embargo recibo ese error por eso la duda de si en alguna parte del codigo no vendra quemado algo para su cuenta.

**Comment by johann04** [comment]
podría revisarlo, pásame exactamente cómo lo estás llamando

**Comment by asalgado0391** [comment]
java -jar /var/www/modular_erp/web-services-layer/SIGNER/xadessignercr.jar sign /var/www/modular_erp/web-services-layer/webroot/keys/2fc6174631db21e610e2/310167998020.p12 xxxx /var/www/modular_erp/web-services-layer/webroot/facturas/2fc6174631db21e610e2_1515447236_FacturaElectronica.xml /var/www/modular_erp/web-services-layer/webroot/facturas/2fc6174631db21e610e2_1515447236_SIGNED_FacturaElectronica.xml
  
Asi es como lo llamo, los archivos
layer/webroot/facturas/2fc6174631db21e610e2_1515447236_FacturaElectronica.xml 
y
layer/webroot/facturas/2fc6174631db21e610e2_1515447236_SIGNED_FacturaElectronica.xml

son los archivos que cargo y genero respectivamente

**Comment by johann04** [comment]
y el send? o lo estás haciendo vos directamente?

**Comment by asalgado0391** [comment]
Ese paso si lo hago yo directamente

**Comment by johann04** [comment]
y estás seguro que ahí estás usando tus credenciales? ya volví a revisar el código de la firma... y está usando los parámetros...

**Comment by asalgado0391** [comment]
Gracias,Si estoy seguro de que los credenciales estan correctos

**Comment by asalgado0391** [comment]
El issuer name es siempre **CN=CA PERSONA JURIDICA - SANDBOX,OU=DGT,O=MINISTERIO DE HACIENDA - SANDBOX,C=CR**
Correcto?

**Comment by johann04** [comment]
mae, ahí no sé de qué parte me está hablando (eso parece que estas hablando del issuer del certificado, que no tiene nada que ver con el error que te está dando), el error te está dando porque el

<Emisor>...</Emisor> tiene que ser el mismo "dueño" del .p12 y el pin... y el mismo de las credenciales de oauth:

cpf-02-0586-0860@stag.comprobanteselectronicos.go.cr

**Comment by johann04** [comment]
la parte que no se vé en el mensaje anterior era un tag de Emisor

**Comment by johann04** [comment]
en el xml... el contenido del tag del Emisor (la cedula) tiene que corresponder con todo

**Comment by asalgado0391** [comment]
correcto en este caso cuando se agrega la identificacion del emisor en el archivo xml unicamente se agregan los 0's solicitados por hacienda para completar 12 caracteres

**Comment by rrc220590** [comment]
A mi me acaba de funcionar perfectamente.

Muchas gracias por su colaboración @johann04

**Comment by rrc220590** [comment]
@johann04  @asalgado0391 
Conocen si en el ambiente de pruebas de hacienda, el receptor recibe el correo?

**Comment by Lcarreno19** [comment]
Una pregunta querido amigo quisiera saber que significan los ID de cada nodo por ejemplo " <ds:Reference Id="xmldsig-df3af3a1-3c83-445d-b65f-d106d30cc54e-ref0" URI=""> " esto es un ID generado dinamicamente o de donde proviene y realizado el XML tal cual como lo tienes en tus ejemplos sin embargo sigue sin funcionarme el error que me arroja como respuesta hacienda es Firma Invalida no se que mas intentar y me siento trancado te puedo enviar mi documento por correo o algo para que me ayudes?

Saludos y muchas gracias

**Comment by rrc220590** [comment]
Esos valores son dinamicos segun su .p12 y el archivo xml de la factura sin firmar. Se crean a partir de ambas cosas, aca hay una explicacion breve https://es.wikipedia.org/wiki/Firma_XML

Yo no estoy generando la firma manualmente, me base en una libreria para firmar documentos xml xades-epes

**Comment by Lcarreno19** [comment]
Bueno en mi caso si tengo que firmarlos manualmente y ya tengo todo armado solo, que tengo algunas cosas que no las tengo claras, sin embargo en que parte del .p12 se encuentran porque no los ubico yo logro abrir el .p12 y extraigo todo lo necesario pero sigue sin darme lo de la firma

**Comment by apokalipto** [comment]
Hay algo extraño. La firma no es válida. Pasos para reproducir:

1) Genero el XML: https://gist.github.com/apokalipto/f7697db0bedab130d3f78f4d4d4000b0
2) Firmar XML: `java -jar xades-signer-cr sign <keyPath> <keyPassword> <xmlInPath> <xmlOutPath>`
3) Enviar documento firmado al API. Respuesta =>  HTTP 202 (estado aceptado)
4) Hacer query para verificarlo: `GET "https://api.comprobanteselectronicos.go.cr/recepcion-sandbox/v1/recepcion/50609021800011190015800100001010000000023199999999"`

La respuesta es la siguiente:  
```xml
<?xml version="1.0" encoding="UTF-8"?>
<MensajeHacienda xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2016/v4.1/mensajeHacienda">
    <Clave>50609021800011190015800100001010000000023199999999</Clave>
    <NombreEmisor/>
    <TipoIdentificacionEmisor>02</TipoIdentificacionEmisor>
    <NumeroCedulaEmisor> 3102111111 </NumeroCedulaEmisor>
    <NombreReceptor/>
    <TipoIdentificacionReceptor>02</TipoIdentificacionReceptor>
    <NumeroCedulaReceptor>3001123208</NumeroCedulaReceptor>
    <Mensaje>3</Mensaje>
    <DetalleMensaje>Este comprobante fue procesado en el ambiente de pruebas, por lo cual no tiene validez para fines tributarios.

La firma del comprobante electrónico no es válida</DetalleMensaje>
```

Saben que podría estar pasando? A ustedes les da el mismo error?

**Comment by tim1991** [comment]
Me paso algunas veces y era por que las fechas de firmado no calzaban con las fechas de la factura, cuando volvía a generar la fecha de la factura y la firmaba se solucionaba

**Comment by apokalipto** [comment]
Pero como puede ser eso? La fecha de firmado la genera la librería al momento de firmar el documento. La fecha del documento se establece previo a firmar el documento. Siempre habrán algunos millisegundos de diferencia.

**Comment by tim1991** [comment]
A lo que me refiero puede que el xml tenga una fecha distinta de un día no se si puedes verificarlo abriéndolo con editor cabo de realizar una prueba y todo paso sin problema  


`Clave: 50620011800030455030100100001010000000015199999999
Fecha: 2018-02-10T16:53:52-06:00
Estado: aceptado
XML:


    50620011800030455030100100001010000000015199999999
    Agustin Gerardo Valverde Castro
    01
    304550301
    Agustin Gerardo Valverde Castro
    01
    304550301
    1
    Este comprobante fue procesado en el ambiente de pruebas, por lo cual no tiene validez para fines tributarios.
    0.00
    50000.00`

**Comment by tim1991** [comment]
El estado 202 siempre lo va a devolver si la factura se envío, ya sea que se envío bien o mal, puedes usar post man para hacer pruebas y ver las cabeceras de retorno de hacienda cuando la envías.

**Comment by tim1991** [comment]
Ahora que recuerdo también me genero  ese error cuando el consecutivo no coincidía con la clave

**Comment by apokalipto** [comment]
Ok! Pura vida! Voy a revisar!

**Comment by apokalipto** [comment]
El problema no era con la firma. El problema era con el XML, y su codificación en base64 a la hora de enviarlo. La respuesta de rechazo debido a que "la firma del comprobante electrónico no es válida, NO NECESARIAMENTE se refiere a la firma digital en sí. Puede estar asociada a problemas con el XML. Adjunto algunas de las posibles causas.

Verificar que la calve esté correcta
La sección H puede contener un número aleatorio o elegido por el desarrollador.
Verificar que el consecutivo de la clave coincida con el consecutivo del XML
Verificar que la fecha de emisión cumpla con el estandar RFC3339: Ej: 2018-02-12T04:05:06-06:00
Verificar que a la hora de serializar el XML en Base64, no contenga los cambios de linea ("\n")
Verificar que la ubicación del emisor coincida con los registros de hacienda
Verificar los namespaces del XML:
<FacturaElectronica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica" xsi:schemaLocation="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica.xsd">

**Comment by VictorMoraB** [comment]
Buenos días @johann04 he estado recientemente probando el firmador pero he estado recibiendo el error este de firma inválida. He estado revisando las sugerencias en este hilo pero aún sigo sin lograr que me acepte el documento correctamente.  Adjunto un xml firmado de prueba y el json del post enviado. El xml tiene la extensión modificada a .txt para subirlo acá.

Le agradezco de antemano si puede darles una ojeada rápida y darme una pista de donde esta el error.

[test request.txt](https://github.com/johann04/xades-signer-cr/files/2195040/test.request.txt)

[50614071800011353003200100001040000000097147193237_signed.txt](https://github.com/johann04/xades-signer-cr/files/2195038/50614071800011353003200100001040000000097147193237_signed.txt)

**Comment by jrujano-zz** [comment]
Estimado Johan , he intentado usar el firmado 

`java -jar ../xadessignercr/release/xadessignercr.jar sign cert.p12 5678 factura.xml outfact.xml
`

Y me arroja el siguiente error

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.ReflectUtils$2 (file:/home/johan/FirmasXADEs/xades-signer-cr-master/xadessignercr/release/xadessignercr.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
xades4j.utils.XadesProfileResolutionException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at xades4j.utils.XadesProfileCore.getInstance(XadesProfileCore.java:223)
	at xades4j.production.XadesSigningProfile.newSigner(XadesSigningProfile.java:112)
	at com.workoutstudioapp.xadessignercr.Signer.sign(Signer.java:57)
	at com.workoutstudioapp.xadessignercr.Cli.main(Cli.java:28)
Caused by: com.google.inject.internal.ComputationException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:46)
	at com.google.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:52)
	at com.google.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:57)
	at com.google.inject.InjectorImpl.initializeBinding(InjectorImpl.java:377)
	at com.google.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:645)
	at com.google.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:581)
	at com.google.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:172)
	at com.google.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:132)
	at com.google.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:651)
	at com.google.inject.FactoryProxy.notify(FactoryProxy.java:48)
	at com.google.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:230)
	at com.google.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:131)
	at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:105)
	at com.google.inject.Guice.createInjector(Guice.java:92)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at xades4j.utils.XadesProfileCore.getInstance(XadesProfileCore.java:219)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2316)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:185)
	at com.google.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:61)
	at com.google.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:31)
	at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:39)
	at com.google.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:35)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:35)
	at com.google.inject.internal.MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 22 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 32 more

**Comment by tim1991** [comment]
Hola puede ser por la versión de JDK si no me equivoco debe ser la 1.8 o
superior

**Comment by jrujano-zz** [comment]
Como me encuentro corriendo sobre un ambiente Linux, cambie la JDK de java-11-openjdk-amd64 a java-8-oracle (1.8.0_181) y funciona correctamente, Quiere decir que el fallo se presenta con la  java-11-openjdk

**Comment by gutiman** [comment]
Hola!!

Tengo el mismo problema que @apokalipto :

`La firma del comprobante electrónico no es válida`

Ya he revisado uno a uno estos puntos:

> Verificar que la calve esté correcta
La sección H puede contener un número aleatorio o elegido por el desarrollador.
Verificar que el consecutivo de la clave coincida con el consecutivo del XML
Verificar que la fecha de emisión cumpla con el estandar RFC3339: Ej: 2018-02-12T04:05:06-06:00
Verificar que a la hora de serializar el XML en Base64, no contenga los cambios de linea ("\n")
Verificar que la ubicación del emisor coincida con los registros de hacienda
Verificar los namespaces del XML

Y todo me parece que está correcto.

Puedo subirles el XML antes de ser firmado a ver si es que hay algo que no veo que sea un error con el XML, pero lo extraño es que incluso aqui dice que es valido:

[https://apis.gometa.org/validar/](https://apis.gometa.org/validar/)

Alguna sugerencia?

**Comment by jrujano-zz** [comment]
> Hola!!
> 
> Tengo el mismo problema que @apokalipto :
> 
> `La firma del comprobante electrónico no es válida`
> 
> Ya he revisado uno a uno estos puntos:
> 
> > Verificar que la calve esté correcta
> > La sección H puede contener un número aleatorio o elegido por el desarrollador.
> > Verificar que el consecutivo de la clave coincida con el consecutivo del XML
> > Verificar que la fecha de emisión cumpla con el estandar RFC3339: Ej: 2018-02-12T04:05:06-06:00
> > Verificar que a la hora de serializar el XML en Base64, no contenga los cambios de linea ("\n")
> > Verificar que la ubicación del emisor coincida con los registros de hacienda
> > Verificar los namespaces del XML
> 
> Y todo me parece que está correcto.
> 
> Puedo subirles el XML antes de ser firmado a ver si es que hay algo que no veo que sea un error con el XML, pero lo extraño es que incluso aqui dice que es valido:
> 
> https://apis.gometa.org/validar/
> 
> Alguna sugerencia?

Chequea la version de java

**Comment by gutiman** [comment]
> Chequea la version de java

1.8.0_181

**Comment by gutiman** [comment]
Acabo de encontrar algo extraño.

La fecha de emision en el XML y el JSON van yyyy-mm-ddThh:nn:ss-06:00, sin embargo, el XML de Hacienda donde dice que tengo un error de firma, el xades:SigningTime dice yyyy-mm-ddThh:nn:ssZ y tiene 6 horas más!!

Es decir, si fechaemision es 2018-10-08T01:00:00-06:00, el xades:SigningTime dice 2018-10-08T07:00:00Z.

Creo que ahi está el problema, pero no se como corregirlo. Nada mas quito el -06:00 de la fechaemision?

**Comment by Lcarreno19** [comment]
bueno no se como sea en JAVA pero en PHP tiene que ser un date('c'), y salen del asunto

**Comment by ndlbass** [comment]
Hola. El horario de la firma yo también lo noté cuando tenía este error, era por la diferencia horaria en donde corría. No te preocupes que no es eso.

En mí caso termino siendo la forma en que quedaba escrito el XML al file, parecía correcto pero no lo era. Si quieres arma un gist con un ejemplo y lo reviso

**Comment by gutiman** [comment]
Aqui les dejo el gist (sin la firma)

https://gist.github.com/gutiman/d07e26d8375f15c01f5465afe544af5c

Si ocupan la firma, me avisan

**Comment by randallramos** [comment]
Hola Gurus,

He estado revisando el foro. Desafortunadamente  no he podido dar con el Error.  En mi caso, es bien extrano, porque unos XML si pasaron, y ahora no pasa ninguno.  No he hecho ninguna modificacion al Programa, ni al firmador.  He comparado los XML y estan identicos, y ya he probado todos los comentarios que han colocado en este foro y nada.  

Me sigue saliendo: Firma no Valida.  

Agradeciendo cualquier ayuda.

Saludos,

Randall

**Comment by tim1991** [comment]
Hola yo hice modificaciones al archivo jar si gustan se los puedo pasar me
funciona bien hasta el día de hoy solo indicarme si gustan probar con mi jar

**Comment by randallramos** [comment]
Si, te lo agradeceria

Asi probamos con ese a ver si resolvemos.

Muchas gracias.

Saludos,

Randall

**Comment by tim1991** [comment]
Esta es otra posible solución

La causa de este problema se debe a que su Llave Criptográfica (o
Certificado) de Hacienda no es válido o fue revocado. Para solucionarlo,
puede seguir el paso 1 (Generar Llave Criptográfica) en el siguiente
recurso;



El Certificado (o Llave Criptográfica) que se debe utilizar son los
identificados como de “Producción”
Favor tener presente que una vez mostrada en pantalla sus credenciales, no
debe presionar en aceptar pues esto revocará las credenciales y deberá
repetir el proceso. En su lugar, proceda a cerrar la ventana del navegador
o utilizar una opción del menú.

**Comment by tim1991** [comment]
Este es el jar https://we.tl/t-CUpOE39ljE

**Comment by randallramos** [comment]
Muchas Gracias,

Tambien voy a validar este punto, y el firmador.

Te mantendre al tanto.

Saludos,

Randall
