### ISSUE TITLE
Error en SignaturePolicyId

### ISSUE THREAD

**Issue by soto13** [johann04/xades-signer-cr#7]
Johann04 veo que a la hora de hacer la firma en el archivo Signer.java justamente en la linea 37 pones la siguiente dirección "https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica" la cual si se quiere hacer MensajeReceptor no dejaría, el enlace correcto para este issue sería "https://tribunet.hacienda.go.cr/docs/esquemas/2016/v4.1/Resolucion_Comprobantes_Electronicos_DGT-R-48-2016.pdf", te agradecería si volvieras a generar el jar con ese issue resuelto

**Comment by johann04** [comment]
Estás seguro que con una versión más vieja?

**Comment by soto13** [comment]
johann04 estoy completamente seguro, en estos momentos con ese enlace podes firmar y enviar el XML FacturaElectrónica sin problemas, pero cuando intentas hacer un XML MensajeReceptor nunca va a dejar y es por el enlace que te digo te adjunto el enlace de estructura del XML MensajeReceptor "https://tribunet.hacienda.go.cr/docs/esquemas/2016/v4.2/MensajeReceptor_4.2.xsd", reitero FacturaciónElectrónica funciona bien pero lo otro no, el XML MensajeReceptor es tan necesario como el XML FacturacionElectronica para Facturacion Electrónica valga la redundancia. Espero puedas actualizar el jar. Saludos

**Comment by soto13** [comment]
Si te fijas en "https://tribunet.hacienda.go.cr/FormatosYEstructurasXML.jsp#" y vas a la versión más reciente y das click al pdf te enviará al siguiente enlace "https://tribunet.hacienda.go.cr/docs/esquemas/2016/v4.2/Modifica_a_la_resolucion_N_DGT_R_48_2016_V4.2.pdf" por eso estoy seguro que si va a funcionar. Saludos otra vez

**Comment by tim1991** [comment]
que extraño por que el mensaje receptor tiene versión 4.2

**Comment by soto13** [comment]
Si es bastante extraño, hazme caso si. Poniendo ese otro enlace queda "universal" por así decirlo para FacturElectronica y MensajeReceptor

**Comment by johann04** [comment]
qué tal si te ayudo a compilarlo? y si te funciona bien me avisas y lo subimos?

**Comment by johann04** [comment]
de hecho hay un archivo build.sh para compilarlo...

**Comment by johann04** [comment]
si estas en windows, lo renombras por build.bat y debería de funcionar... (tienes que instalar maven)

**Comment by soto13** [comment]
Gracias habia tratado de generar el JAR antes desde eclipse y no me dejaba, gracias a vos ya pude desde el .sh y si. El error que tenía en Mensaje Receptor se solucionó y firma bien tanto FacturaElectrónica como MensajeReceptor. Gracias por el aporte a la comunidad.

**Comment by johann04** [comment]
mae, le puse permisos en el repo, por si quiere subir el cambio en el código y el jar compilado

**Comment by soto13** [comment]
Intenté subir los cambios, pero me sale error en los permisos
![403](https://user-images.githubusercontent.com/25696416/40249123-452acdbc-5a8f-11e8-8c6f-69f9fa9a24cf.png)

**Comment by johann04** [comment]
Supongo que no has aceptado la invitación al repo...

<img width="743" alt="screen shot 2018-05-18 at 11 46 15 am" src="https://user-images.githubusercontent.com/5248111/40249736-2a1b43ba-5a91-11e8-8089-2d2c30491eec.png">

**Comment by soto13** [comment]
No me sale, envíame el link de la invitación. Ya sea por aquí o por correo, mi correo es ezesoto13@gmail.com

**Comment by soto13** [comment]
Listo, el link me llegó al correo no lo había visto
