### ISSUE TITLE
Consulta sobre licencia del código de este repositorio

### ISSUE THREAD

**Issue by psequeirag** [johann04/xades-signer-cr#9]
Buenas,

Este repositorio está interesante, muchas gracias por publicarlo. Nada más quería preguntarle sobre qué licencia es que se está publicando el código? Apache 2? GPLv3? Otra?

Muchas gracias.

**Comment by johann04** [comment]
Pues ni le he hecho cabeza, cuál es la más abierta?

**Comment by psequeirag** [comment]
Depende de tu preferencia sobre lo que quieres permitir a otros hacer:

* Apache 2 permite a otros tomar tu código e incorporarlo en un sistema propietario sin que tengan la obligación de liberar los cambios que le hagan o las partes que agregen al programa por su cuenta. Apache 2 es la que veo usarse con mucha frecuencia en proyectos hechos con Java.
* GPLv3 es la que obliga a otros a publicar sus propios cambios y adiciones bajo términos similares, de manera que otras personas no puedan crear y redistribuir su propio software bajo licencia propietaria si usaron tu código licenciado bajo GPLv3.
* Affero GPLv3 va más allá que la GPLv3 y además obliga a otros usando tu código a que publiquen sus cambios y adiciones aún si sólo están corriendo el software en sus propios servidores (porque al servir aplicaciones y servicios web técnicamente no estás redistribuyendo el software que corre en el servidor, entonces los requisitos de publicar el código fuente de la GPLv3 no  aplicarían).

Espero que estas explicaciones hayan ayudado a aclarar las diferencias un poco.

En mi caso, creo que no tendría problema con ninguna de las tres, pero sí es importante que puedas establecer de manera clara bajo qué términos es que estás publicando este trabajo a fin de dar seguridad a cualquiera que desee aprovecharlo, como creo que es tu intención.

De hecho entiendo que, en principio, aunque publicaste tu código aquí en GitHub, eso en sí mismo no le da derecho a ninguna persona de utilizarlo de ninguna manera (se asume que por defecto todos tus derechos de autor te los reservas para tí mismo, incluído el derecho de que yo pueda hacer una copia de lo que publicaste para bajarlo a mi computadora y probarlo, a menos que indiques lo contrario).

Algunas referencias:
* https://digitizor.com/apache-license-vs-the-gpl/
* https://resources.whitesourcesoftware.com/blog-whitesource/open-source-licenses-trends-and-predictions

**Comment by psequeirag** [comment]
Vale aclarar, siendo tú el autor original de todo este código, indistintamente de la licencia que escojas para este repositorio, entiendo que no estarías impedido de escojer otros términos (incluso hacer software propietario con éste), siempre y cuando se trate de lo que escribiste y no lo que otros hayan aportado. Lo digo en caso de que ya hayas utilizado algo de esto en otro proyecto tuyo y te preocupe que eso afecte tus opciones para aplicar en este repositorio.

**Comment by johann04** [comment]
Listo, apache 2
